name: CI
on:
  push:               # any branch
  workflow_dispatch:  # manual run button
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Hello, World!"
